#!/bin/sh
#Waiting for HDD-plugin to finish...
echo '#overmount:/opt'
n=1
while [ ! -d  /tmp/hdd/root/opt ] ; do
 sleep 3
 [ $n -gt 30 ] && break
 let n+=1
 echo '#waiting for hdd..'
 echo $n
done
#bind rss scripts directory:
if [ ! -f /opt/.overmounted ];then
    echo '#overmount start'
    mount -o bind /tmp/hdd/root/opt /opt
    touch /opt/.overmounted
    echo '#overmount end'
fi

