#!/bin/sh
#Waiting for HDD-plugin to finish...
echo '#copy ewcp'

#check if storage
. /usr/local/etc/storage


n=1
while [ ! -d /tmp/www/ ] ; do
 sleep 3
 [ $n -gt 30 ] && break
 let n+=1
 echo '#waiting /tmp/www'
 echo $n
done
#bind rss scripts directory:

cp -r ${storage}/ewcp/*	/tmp/www/
chmod +x /tmp/www/cgi-bin/*
