#!/tmp/hdd/root/opt/bin/bash
#(c)vonck 2010
#LICENCE: GPL
#Put this file in /tmp/hdd/root/unicgi/cgi-bin
#depends on optware + mplayer binary from the xtreamer forum.
#I would prefer to use python or another scripting language, but it should be easy to install.
#Help needed!!!; I don't know what the f***k I'm doing, my bash scripting experience is minimal.
#
#Security Bugs:
#URL and FORMAT are not validated against shell injection.
#

echo "Content-type: text/plain"
echo ""

echo "<rss>"
#Commands+Logging
echo "<!--Logging+Debug here:"
echo "[r0.0.1]"
killall mplayer -9
echo "-->"
#The rest of the rss output
echo "<channel><title>rss_streamer_stopall</title>"
echo "<description>rss_streamer_stopall</description>"
echo "<item><title>- - -</title></item>"
echo "<item><title>All rss_streamer downloads are stopped now.</title></item>"
echo "</channel>"
echo "</rss>"



