#!/bin/sh

prefix="/cb3pp"

PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=thttpd
DAEMON=${prefix}/sbin/${NAME}
DAEMON_OPTS="-d /tmp/cbwww -p 82 -nos"



test -x $DAEMON || exit 0

if [ -z "$1" ] ; then
    case `echo "$0" | sed 's:^.*/\(.*\):\1:g'` in
        S??*) rc="start" ;;
        K??*) rc="stop" ;;
        *) rc="usage" ;;
    esac
else
    rc="$1"
fi

case "$rc" in
    start)
	echo "Starting web server: $NAME"
	mkdir /tmp/cbwww
	ln -s ${prefix}/share/www /tmp/cbwww/
	ln -s /scripts /tmp/cbwww/
	nice -n 30 $DAEMON $DAEMON_OPTS
        ;;
    stop)
    	rm /tmp/cbwww/*
    	rmdir /tmp/cbwww
        if [ -n "`pidof $NAME`" ]; then
            echo "Stopping web server: $NAME"
            killall $NAME 2> /dev/null
        fi
        ;;
    status)
	if [ -n "`pidof $NAME`" ]; then
	    echo $NAME is running
	    exit 0
	else
	    echo $NAME is stopped
	    exit 1
	fi
	;;
    try-start)
	if [ -n "`pidof $NAME`" ]; then
	    echo $NAME is running
	    exit 0
	else
	    echo $NAME is stopped, starting it
            "$0" restart
	fi

	;;
    restart)
        "$0" stop
        sleep 1
        "$0" start
        ;;
    *)  
        echo "Usage: $0 (start|stop|restart|status|try-start|usage)"
        ;;
esac

exit 0
