#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010  Serge A. Timchenko
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

local debugfile=/tmp/nnb.log
echo -n >$debugfile

#local CACHEPATH=/tmp
#local MSDL=/usr/local/etc/translate/bin/msdl
#local arg_url=http://www.zoomby.ru/music/search?q=Serebro
#local arg_url=http://www.zoomby.ru/music/search?q=Alice
#local arg_url=http://www.zoomby.ru/music/collections/featured?page=26
#local XSLTPROC=/usr/local/bin/xsltproc

local DATAPATH=$BASEPATH/app/zoomby
#local DATAPATH=/tmp

local PAGEFILE=$CACHEPATH/zoomby.page
local PAGEXML=$CACHEPATH/zoomby.xml

#echo $DATAPATH >$debugfile
#echo $PAGEFILE >>$debugfile
#echo $PAGEXML >>$debugfile
#echo $arg_opt >>$debugfile

$MSDL -q -o "$PAGEFILE" -p http "$arg_opt"
if [ -f "$PAGEFILE" ]; then
   local pages=`grep '<td valign="top"><div onClick="window.location.href=' $PAGEFILE | sed -r 's/^.*>([0-9]*)<\/div><\/td>/\1/'`
#   echo pages=$pages >>$debugfile

   if [ "$pages" = "" ]; then
    pages=1
   fi

cat > $PAGEXML <<EOF
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
 <channel>
  <title>ZOOMBY.RU</title>
  <link>http://zoomby.ru</link>
  <description>ZOOMBY.RU</description>
  <language>ru</language>
EOF
echo -n "  <pages>"$pages >>$PAGEXML
echo "</pages>" >>$PAGEXML

#echo pages=$pages >>$debugfile

   if [ -x $XSLTPROC ]; then
#     $XSLTPROC --encoding utf-8 --html $DATAPATH/music_videos.xslt $PAGEFILE 2>/dev/null | sed '1d' >> $PAGEXML
     $XSLTPROC --html $DATAPATH/music_videos.xslt $PAGEFILE 2>/dev/null | sed '1d' >> $PAGEXML
   fi

cat >> $PAGEXML <<EOF
 </channel>
</rss>
EOF

   rm -f $PAGEFILE
fi

if [ -f "$PAGEXML" ]; then
 cat $PAGEXML
 rm -f $PAGEXML
fi

