#!/bin/sh

TITLE='Hello, world!'

cat <<EOF
Content-type: text/xml

<application title="$TITLE">
<arg>$arg_opt</arg>
`echo "<echo/>"`
`export | awk '{print "<export>" $2 "</export>"}'`
<set><![CDATA[`set`]]></set>
</application>
EOF
