#!/bin/sh


# Start all init scripts in /cb3pp/etc/init.d
# executing them in numerical order.
#


PATH=$PATH:/cb3pp/bin:/cb3pp/sbin
export PATH

for i in /cb3pp/etc/init.d/S??* ;do
     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done
