#!/bin/sh
#Waiting for HDD-plugin to finish...
echo '#overmount:/usr/local/bin/scripts'
n=1
while [ ! -d  /tmp/hdd/root/opt ] ; do
 sleep 3
 [ $n -gt 30 ] && break
 let n+=1
 echo '#waiting for hdd..'
 echo $n
done
#bind rss scripts directory:
if [ ! -f /usr/local/bin/scripts/.overmounted ];then
    echo '#overmount start'
    mount -o bind /tmp/hdd/root/scripts_overmounted /usr/local/bin/scripts
    touch /usr/local/bin/scripts/.overmounted
    echo '#overmount end'
fi

